# Generated by Django 2.0.2 on 2020-03-31 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200324_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=20)),
                ('cidade', models.CharField(choices=[('juazeiro', 'Juazeiro do Norte'), ('crato', 'Crato'), ('barbalha', 'Barbalha')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
