# Generated by Django 2.0.2 on 2020-04-11 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200331_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='usuario',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='perfil',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Perfil'),
        ),
    ]
