# Generated by Django 2.0.2 on 2020-05-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200411_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
