# Generated by Django 3.0.6 on 2020-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_anuncio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='foto_capa',
            field=models.ImageField(default=0, upload_to='imagens'),
            preserve_default=False,
        ),
    ]
