# Generated by Django 3.0.6 on 2020-06-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_anuncio_foto_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='foto_capa',
            field=models.ImageField(upload_to='media/imagens'),
        ),
    ]
