# Generated by Django 3.0.6 on 2020-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200622_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
