# Generated by Django 3.0.6 on 2020-07-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_anuncio_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], max_length=20)),
                ('adotante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Perfil')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Anuncio')),
            ],
        ),
    ]
