# Generated by Django 3.0.6 on 2020-07-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='adotante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Perfil'),
        ),
    ]
